## try~except Exception as e

```python
try:
    print(computer)
except Exception as e:
    print(c)
    
computer라는 변수가 정의되지 않았기 때문에 NameError가 발생합니다.
하지만 except Exception as e는 NameError를 c롤 통해 접근이 가능하도록 만들어 줍니다.
```

